### ISSUE TITLE
bug with picture info with none selected

### ISSUE THREAD

**Issue by derpac** [alvierahman90/derpic#14]
when you select two or more images and then de-select the images the info area fills with the info of the one that was first clicked. also same ish issue when you select multiple images. this needs to be removed should be easy fix!

**Comment by derpac** [comment]
can't seem to replicate this bug, perhaps the faires came and fixed it or there are more specifc circumstances that Ive forgotted

**Comment by alvierahman90** [comment]
might have been fixed by the deleting images after upload bug! seems like it might be related but if it’s gone then we can close ig 🤷 Sent from my iPhoneOn 12 Aug 2024, at 15:08, Derry Packer ***@***.***> wrote:﻿
can't seem to replicate this bug, perhaps the faires came and fixed it or there are more specifc circumstances that Ive forgotted
